# Generated by Django 5.0.4 on 2024-10-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumetemplate_resume_education_resume_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
