# Generated by Django 5.1.2 on 2024-12-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_remove_jobapplication_salary_vacancy_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['created_at']},
        ),
    ]
